name: watchman_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.0
  lottie: ^2.6.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  country_code_picker: ^3.0.0
  syncfusion_flutter_datepicker: ^23.1.40
  intl: ^0.18.1


  #firebase_dependencies
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0



  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/gif/

  fonts:
    - family: Figtree-Regular
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf

    - family: Figtree-Medium
      fonts:
        - asset: assets/fonts/Figtree-Medium.ttf

    - family: Figtree-Bold
      fonts:
        - asset: assets/fonts/Figtree-Bold.ttf

    - family: Figtree-SemiBold
      fonts:
        - asset: assets/fonts/Figtree-SemiBold.ttf